import { geistSans, geistMono, jost } from "./fonts";
import "./globals.css";
import FilterProvider from "./components/context/FilterProvider";
import CartProvider from "./components/context/CartProvider";
export const metadata = {
  title: "Game store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${jost.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FilterProvider>
          <CartProvider>{children}</CartProvider>
        </FilterProvider>
      </body>
    </html>
  );
}
